### PR TITLE
Remove gin dependency

### LINKED ISSUE #8: Don't use gin
There are only 3 super simple http endpoints. no need for a framework like gin, this can be handled using `net/http`

### PR DESCRIPTION
**Pull request by alexanderstephan**
This PR
- closes #8 
- adds synchronization to the map of streams in the `selfstream` package.
- adds some basic tests to ensure functionality of the handlers.

This safes actually a lot of dependencies and the API should hopefully not change too much in the near future. 
The binary also shrinks by ~3MB.

### CODE REVIEW

**Comment by joschahenningsen** [comment]
Don't worry about the codeql issues, marked them as false positive since what comes in here is **not** user-generated.

**Comment by joschahenningsen** [comment]
> Okay, thanks for the info!
> 
> I also removed `onRecordDone` since it was deprecated. Is this fine or should I add it again?

Removing it should be fine 👌

**Comment by alexanderstephan** [comment]
I am marking this as draft again, since I want to try if I can also write a nice testcase for this package.

**Review by joschahenningsen — APPROVED** [review]
Looks great, thanks! Especially love the tests :)

**Pull request merged**
